"""
Django settings for qualix project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'SECRET_KEY'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'qualix.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'qualix.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/uploads/'
MEDIA_ROOT = BASE_DIR / 'uploads'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

QUALIX_BASEURL = 'https://slb.medv.ru/api/v2/'
QUALIX_CRT = """
-----BEGIN CERTIFICATE-----
MIIDRjCCAi4CAwX1qjANBgkqhkiG9w0BAQsFADB5MQswCQYDVQQGEwJSVTEMMAoG
A1UECAwDVWZhMQwwCgYDVQQHDANVZmExDDAKBgNVBAoMA3NsYjEOMAwGA1UECwwF
ZGltb24xDDAKBgNVBAMMA2V0YzEiMCAGCSqGSIb3DQEJARYTc3VwcG9ydEBzbGIu
bWVkdi5ydTAeFw0yMDA4MjcxODM0MThaFw0yMTA4MjcxODM0MThaMFcxCzAJBgNV
BAYTAlJVMQ8wDQYDVQQIDAZNb3Njb3cxDzANBgNVBAcMBk1vc2NvdzENMAsGA1UE
CgwEVGVzdDEXMBUGA1UEAwwOdGVzdEB0ZXN0LnRlc3QwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQC76eyroh2mFLQOTVxjD/ZKnWB7QexLgcjEyTfKfN2C
DBSGtFgxPIsP/uzo2VDFc4WIitPqREzVFHr5zSCroH7rHS6IrYmMH3lOTDwquMt5
7Y+D85szjLwgRfgT4ObpXY1DtkgbJUfeQIK40GRPXulGyH1sm0rW5bEWIeFAKBtm
gFMbvygqRCp8WVajSTBTVMY4cUtKu5ihtCiqmquHNf+nT2FKy+7MSgYOIOed1opB
EhYX/8yFUpRlrRegI/5ibsy7S7gO5JznCGrARjTuxSdYEp6CrLUs7GZ8mqYWFCb+
SICdhoJhIPUWANXCowNe2zpG3hSts+sYgwEz1LhHczFFAgMBAAEwDQYJKoZIhvcN
AQELBQADggEBACaKzecbLkEYltKb576NG6f1fhf5LHU2JT8LZz+ZavEMi9RQOBnH
BgzRiuLBkwy7LUUdH/eCmOboDHZ/udMpZlruo9exGbSqlUSZI51fwHVWxxnRFxPx
zY5XFbpOVpnSf5g2foUD3OnWCwJOLF92PzlVV2IBJ/fI+TgIrITSFhkfiqvOv4MN
GzjnYohbPAUoTrnuACOZS1/ykR4KmZlvH5mjzEHkiegXhGmbgjGBfGJr9FhSncws
mUcZruc/NnSRVadd4hoKCFO2iB+ghGF3cBdtZeCEeOhQ4xD78I1y8OpwTvIMUZMW
Uio5BMZE5I93wR81WPxmGOzMUFezipPB+h8=
-----END CERTIFICATE-----
"""

QUALIX_KEY = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC76eyroh2mFLQO
TVxjD/ZKnWB7QexLgcjEyTfKfN2CDBSGtFgxPIsP/uzo2VDFc4WIitPqREzVFHr5
zSCroH7rHS6IrYmMH3lOTDwquMt57Y+D85szjLwgRfgT4ObpXY1DtkgbJUfeQIK4
0GRPXulGyH1sm0rW5bEWIeFAKBtmgFMbvygqRCp8WVajSTBTVMY4cUtKu5ihtCiq
mquHNf+nT2FKy+7MSgYOIOed1opBEhYX/8yFUpRlrRegI/5ibsy7S7gO5JznCGrA
RjTuxSdYEp6CrLUs7GZ8mqYWFCb+SICdhoJhIPUWANXCowNe2zpG3hSts+sYgwEz
1LhHczFFAgMBAAECggEAZcwosSYGp8UJccII7YVlKDCvZrZkutbZG3niJmiUWvIO
YJbsO+gPcZ/pWY74ia62RSzn9j3/3WLV5+Nu8mrktpu9bL+OBwG55me4JHCtkiTW
nWXnyvpPo7Aj3yj0DrHmaCskTshYcZdC+bmyzaid+QF9qMtLtLUDxPifnPDdPx4Q
J7O9S3AwUdYGfGzt6SWVaso+U18+ymdOUS2B4Y54DekmUYAHFgZ47pVi8cjcPWtC
oBnWXmzEncdpjDgIlRFVeU8w3nmZTkUxiuUtV87iXvekHI1azMDxZu3xUWZdWZn+
UL7RlA+RGumkrAFYQrVp4CoVyg3GajlZU4zutd3VlQKBgQD2aoXflAMWD9WFt32a
E6ED9LlU7ZGzHNhw/EhzNh+DisY4qiAERlXgZz9bJ3Rb7ljGp3WFo79uvDH7H5lI
DKBjHMgp39JouqFjnWKZzH+vz5XhvKuwCnx3jLoYsK8rLIu5sZvhkTyHMz1yCszK
JsO1nR1DZsWzyG7KghK4LCNRYwKBgQDDOOopOCMg4jvO4mlEZJTFRMfwult3+ika
s5CIuOs1kR3BGXn2sciEBHG6rJ+dlrsvTJHuY9shfYZHPgp8jjG6cFbZGQoHS5W/
QKn2V3LFK9+b/+b3JSLJD3M8qb8gO70jXwxSPQginhOJ+vt6pBpIa8ysEa7WlPMc
3dPWc8EHNwKBgAismUfUiwNEzWxmmCpLVJiyDbAaqM1YT5oyl05O8m8L/IxUGMpt
u2op2EYaLnNqAYAEtxNcP0njoBLJ+vhZUXALvFQVB/Ad2b6K9MSbOUd0FD+dB6Ir
zFPdBVQHLDNl3wlLYkRfe3T67cfM74aSNMN442XTAVSh0pyYVZZcH2YnAoGAUVw5
8r3LnhvLEzi26GMGwYQd08zG7CSc1tz5IpH2rNdy0BQ/CTokuChmAYeJ6hJ0pozB
0Nla7QU0XiKUGj7kqK/C8i2GSW4N1awsaVcepN/ZDFnFN0EJ00OWIjUYS2W6OLCX
IPsAlfTNbdbk0cLslTwgC6I+/H0NKP2mGJ0bWFcCgYEArpuAo9RSX9vkbdYkOi63
zcdIXjwxJw2ddKzp1EMRuEMU6oIFaXoz1MRVsys2JB/K1WGQO9afjIvgpoITPEe4
1SVdHIHamTjjcEJXlZ6rn1oiMkqchRNLyEiW5C1+c20uvV1NwoR9Tlr+ryGJ7UXW
QeZTD6mCdLOxGaN/FMvOUdQ=
-----END PRIVATE KEY-----
"""

try:
    from .local_settings import *
except ModuleNotFoundError:
    pass